

import { Inter } from "next/font/google";
import "./globals.css";
import {Nav, Footer} from "./component";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pengabdian Kepada Masyarakat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className="scroll-smooth bg-[#F5E7B2]">
        <Nav />
        {children}
        <Footer/>
        </body>
    </html>
  );
}
